version: '3.8'

services:
  # Spring Boot 애플리케이션 서비스
  app:
    build: .
    container_name: daejeon-backend
    ports:
      - "8081:8081"
    environment:
      # .env 파일에서 MYSQL_USER와 MYSQL_PASSWORD 값을 가져옵니다.
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql_db

  # MySQL 데이터베이스 서비스
  mysql_db:
    image: mysql:8.0
    container_name: daejeon_db
    environment:
      # .env 파일에서 정의된 변수들을 가져와 MySQL 컨테이너 환경을 설정합니다.
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ai_challenge_db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "4000:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
