version: '3.8'

services:
  # Spring Boot 애플리케이션 서비스
  app:
    build: .
    container_name: daejeon-backend
    ports:
      - "8081:8081"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # MySQL DB 컨테이너의 상태가 'healthy'가 될 때까지 기다립니다.
    depends_on:
      mysql_db:
        condition: service_healthy

  # MySQL 데이터베이스 서비스
  mysql_db:
    image: mysql:8.0
    container_name: daejeon_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ai_challenge_db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "4000:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    # DB 컨테이너의 상태를 주기적으로 확인하는 healthcheck 설정
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u $$MYSQL_USER -p$$MYSQL_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  mysql_data:
